### ISSUE TITLE
Waiting for H5P JavaScript to load...

### ISSUE THREAD

**Issue by Oleec** [learntube/lms3h5p#1]
hey, thanks for your work on this plugin.  I did the installation using the extensions in my typo3 backend page, installations was ok, but trying to use it happens the following: 
![image](https://user-images.githubusercontent.com/105202937/222675490-0f1017e0-7bd0-4478-b6be-4ae0a5e8278f.png)
and I can't move forward.  if I click on create content I got an error. 
![image](https://user-images.githubusercontent.com/105202937/222675761-24c31f87-1863-4ab8-86f2-3fb397e5a983.png)

I will highly appreciate any help to make it work and test. 
thanks and best regards, 
Oscar

**Comment by desaisagar** [comment]
I know, it's too late but are you still facing the issue? It seems the issue with the configuration.

**Comment by liayn** [comment]
#5 is maybe related

**Comment by desaisagar** [comment]
The fix has been merged.
